services:
  webmtg-document:
    container_name: webmtg-document
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./docs/projects:/app/projects
      - ./docs/mkdocs.yml:/app/mkdocs.yml
    restart: unless-stopped

  webmtg-frontend:
    container_name: webmtg-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0"
